castleapartments/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('home.urls')),
    path('properties/', include('property.urls')),
    path('sellers/', include('seller.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('home/', include('home.urls')),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index")
]

seller/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="seller-index"),
    path('update_seller/<int:id>', views.update_seller, name="update_seller"),
    path('<int:id>', views.get_seller_by_id, name="seller_details"),
]

seller/models.py
from django.contrib.auth.models import User
from django.db import models

# Create eayour models here.
class Seller(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        user = User.objects.filter(id=self.user_id).values()
        return f'{user[0]["first_name"]} {user[0]["last_name"]}'

user/models.py
from django.contrib.auth.models import User
from django.db import models

class UserImage(models.Model):
    image = models.CharField(max_length=999)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.image

seller/forms/seller_form.py
from django.forms import ModelForm, widgets
from django import forms
from seller.models import Seller

class SellerUpdateForm(ModelForm):
    image = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Seller
        exclude = [ 'id' ]
        widgets = {
            'name': widgets.TextInput(attrs={'class': 'form-control' }),
        }

Seller/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'Seller/index.html')

seller/views.py
from seller.models import Seller
from django.shortcuts import render, get_object_or_404, redirect
from seller.forms.seller_form import SellerUpdateForm


def index(request):
    sellers = Seller.objects.all().values("user__first_name", "user__last_name",
                                          "user__email", "user__userimage__image", "id")
    return render(request, 'seller/index.html', {
        'sellers': sellers
    })


def get_seller_by_id(request, id):
    res = Seller.objects.filter(user_id=request.user.id).values_list('pk', flat=True)
    if request.user.is_authenticated:
        seller_id=res.values()[0]['id']
        return render(request, 'seller/seller_details.html', {
            'seller': get_object_or_404(Seller, pk=id),
            'prufa': seller_id
        })
    else:
        return render(request, 'seller/seller_details.html', {
            'seller': get_object_or_404(Seller, pk=id)
        })


def update_seller(request, id):
    instance = get_object_or_404(Seller, pk=id)
    if request.method == 'POST':
        form = SellerUpdateForm(data=request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('seller_details', id=id)
    else:
        form = SellerUpdateForm(instance=instance)
    return render(request, 'seller/update_seller.html', {
        'form': form,
        'id': id
    })

templates/seller/index.html
{% extends 'base.html' %}

{% block content %}
<h3 id="title">Sellers</h3>
    <div class="sellers">
        {% for seller in sellers %}
            {% include 'seller/single_seller.html' with seller=seller %}
        {% endfor %}
    </div>


{% endblock %}

templates/seller/seller_details.html
{% extends "base.html" %}
{% block content %}
    <h1 id="title">{{ seller.user.first_name }} {{ seller.user.last_name }}</h1>
    <div class="seller-cont">
        <div class="seller-img-div">
            <img class="seller-img-det" src="{{ seller.user.userimage_set.first.image }}"/>
        </div>
    <div id="seller-info-div">
        <a href="mailto:{{ seller.user.email }}?subject=Castle Apartments" id="email" title="{{ seller.user.email }}">Send email</a>
        <br>
        {% if user.is_authenticated  %}
            {% if seller.id == prufa %}
                <a href="{% url 'update_seller' seller.id %}" class="block btn btn-primary" id="edit-profile-btn">Edit Profile</a>
            {% endif %}
        {% endif %}
    </div>
    </div>
    <form>
    <input type="button" value="Back" class="btn btn-primary pull-right" style="clear:both; margin: 10px 0" onClick="javascript:history.go(-1)"/>
    </form>
{% endblock %}

templates/seller/single_seller.html
<div class="well seller" id="container_seller">
    <div class="single">
        <a href="/sellers/{{ seller.id }}">
            <div id="row_seller">
                <div id="col_seller">
<<<<<<< HEAD
                    <img class="seller-img" src="{{ seller.image }}"/>
                    <h4 class="caption">{{ seller.first_name}} {{seller.last_name }}</h4>
=======
                    <img class="seller-img" src="{{ seller.user__userimage__image }}"/>
                    <h4 class="caption">{{ seller.user__first_name}} {{seller.user__last_name }}</h4>
>>>>>>> b8e5ba81d4b2337dfc852bca659cbfce16e7ce5f
                </div>
            </div>
        </a>
    </div>
</div>

templates/seller/update_seller.html
{% extends "base.html" %}
{% block content %}
    <div class="update_seller">
    <form class="form form-horizontal" action="{% url 'update_seller' id %}" method="post" id="input-update-box">
        {% csrf_token %}
        {{ form }}
        <input type="button" value="Back" class="btn btn-primary pull-right" id="back-seller" onClick="javascript:history.go(-1)"/>
        <input type="submit" value="Update" class="btn btn-primary pull-right" style="clear:both; margin: 10px 0"/>
    </form>

    </div>
{% endblock %}